{% set name = "7za" %}
{% set version = "19.00" %}
{% set version_nodot = version.replace(".", "") %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: 7z-extra.7z
  url: https://www.7-zip.org/a/7z{{ version_nodot }}-extra.7z
  sha256: af6eca1c8578df776189ee7785ab5d21525e42590f788c4e82e961a36c3a5306

build:
  number: 0
  skip: true  # [not win]

requirements:
  build:
    - 7za

test:
  commands:
    - 7za --help

about:
  home: https://www.7-zip.org/
  license: LGPL v2.1
  license_family: LGPL
  license_file: license.txt
  summary: 'A file archiver with a high compression ratio'

extra:
  final: true
  recipe-maintainers:
    - scopatz
